"""
Citation System for UK Autism Assistant
Formats source attributions and maintains transparency
"""

from typing import List, Dict, Any, Set, Tuple
from datetime import datetime
import pytz

class CitationFormatter:
    def __init__(self):
        self.uk_timezone = pytz.timezone('Europe/London')
    
    def format_sources(self, sources_used: List[Tuple[str, str, str]]) -> str:
        """
        Format sources into a clean citation block
        sources_used: List of (source_name, url, title) tuples
        """
        if not sources_used:
            return ""
        
        citation_lines = ["**Sources:**"]
        
        # Remove duplicates while preserving order
        seen = set()
        unique_sources = []
        for source in sources_used:
            if source not in seen:
                seen.add(source)
                unique_sources.append(source)
        
        for source_name, url, title in unique_sources:
            # Format citation based on source type
            if "gov.uk" in url:
                citation = f"• **{source_name}** - {title} ({url})"
            elif "nhs.uk" in url:
                citation = f"• **NHS** - {title} ({url})"
            elif "autism.org.uk" in url:
                citation = f"• **National Autistic Society** - {title} ({url})"
            elif "hounslow.gov.uk" in url:
                citation = f"• **Hounslow Council** - {title} ({url})"
            else:
                citation = f"• **{source_name}** - {title} ({url})"
            
            citation_lines.append(citation)
        
        return "\n".join(citation_lines)
    
    def extract_inline_citations(self, response_text: str) -> Set[str]:
        """Extract inline citations from response text"""
        import re
        
        # Find citations in square brackets like [NHS] or [National Autistic Society]
        citations = re.findall(r'\[([^\]]+)\]', response_text)
        return set(citations)
    
    def add_transparency_note(self, response: str, chunks_used: int, model_used: str) -> str:
        """Add transparency information about AI generation"""
        current_time = datetime.now(self.uk_timezone).strftime("%d %B %Y at %H:%M")
        
        transparency_note = f"""

---
*This response was generated by Maya AI assistant on {current_time}, using information from {chunks_used} trusted UK autism sources. Please verify important information with the original sources listed above.*"""
        
        return response + transparency_note
    
    def create_source_disclaimer(self) -> str:
        """Create disclaimer about information accuracy and AI limitations"""
        return """
**Important:** This information is for guidance only. For personalised advice:
• **Medical questions:** Contact your GP or call NHS 111
• **Legal/SEND issues:** Contact IPSEA, Citizens Advice, or a qualified solicitor  
• **Crisis support:** Call 999, contact Samaritans (116 123), or go to A&E

Always verify information with official sources."""